name: Packaging and deployment tests
on: [ 'pull_request' ]


jobs:
  packaging-and-deployment-tests-clang:
    name: Packaging and deployment tests clang-14
    uses: ./.github/workflows/reusable_packaging_and_deployment.yml
    with:
      os: ubuntu-22.04
      compiler: clang-14
      cmake-version: 3.23.5

  packaging-and-deployment-tests-gcc:
    name: Packaging and deployment tests gcc-12
    uses: ./.github/workflows/reusable_packaging_and_deployment.yml
    with:
      os: ubuntu-22.04
      compiler: gcc-12
      cmake-version: 3.23.5
